---
APPLY_FIXES: none

CONSOLE_REPORTER: true
CONSOLE_REPORTER_SECTIONS: true
OUTPUT_DETAIL: detailed
GITHUB_COMMENT_REPORTER: false

JSON_FILTER_REGEX_EXCLUDE: '(tsconfig.json)'

DISABLE:
  - SPELL
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
